name = "amkads"
main = "src/index.ts"
account_id = "7fb87506eb8060cc8da12e044c15a6fb"
compatibility_date = "2024-01-01"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "amkads-portfolio"
database_id = "3f516c4b-9a23-4048-b1f8-e9ce2e2f6962"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "amkads-media"
