name = "amkads"
main = "src/index.ts"
account_id = "7fb87506eb8060cc8da12e044c15a6fb"
compatibility_date = "2024-01-01"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "amkads-portfolio"
database_id = "e1a91113-bcdd-4dca-95ce-69973c9c9625"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "amkads-media"
